CREATE TABLE "mytable" (
  "use sales;" text
);

INSERT INTO "mytable" ("use sales;")
VALUES
('Create View Sales_Transactions AS'),
('SELECT COUNT(*) AS Total_Transactions FROM sales.transactions;'),
('#1. Calculate the total number of sales transactions.'),
('Select * from Sales_Transactions;'),
('Create View Sales_Customers AS'),
('Select Count(*) from sales.customers;'),
('#2. Calculate the total number of sales customers.'),
('Select * from Sales_Customers;'),
('Create View First_Five_Records AS'),
('Select * from sales.transactions Limit 5;'),
('#3. Select the first 5 records from the sales.transactions table.'),
('Select * from First_Five_Records;'),
('Create View Market_Code AS'),
('Select * from sales.transactions'),
('Where market_code = ''Mark001'';'),
('#4. Select all the records from the sales.transactions table where Market Code is ''Mark001''.'),
('Select * from Market_Code;'),
('Create View Currency AS'),
('Select * from sales.transactions'),
('Where currency = ''USD'';'),
('#5. Select all the records from the sales.transactions table where currency is ''USD''.'),
('Select * from Currency;'),
('Create View Date_From_Sales AS'),
('Select sales.transactions.*'),
('Inner Join sales.date ON sales.transactions.order_date = sales.date.date;'),
('#6. Join both the tables transactions and date from sales using Inner Join.'),
('Select * from Date_From_Sales;'),
('Create View All_Transactions_Records AS'),
('Select sales.transactions.*'),
('Inner Join sales.date ON sales.transactions.order_date = sales.date.date'),
('Where sales.date.year = 2020;'),
('#7. Find out all the transactions records takes place in the year 2020.'),
('Select * from All_Transactions_Records;'),
('Create View SUM_Transactions_Amount AS'),
('Select Sum(sales.transactions.sales_amount) from sales.transactions'),
('Inner Join sales.date ON sales.transactions.order_date = sales.date.date'),
('Where sales.date.year = 2020;'),
('#8. Calculate the total number of sales transactions and sales amount.'),
('Select * from SUM_Transactions_Amount;'),
('Create View Sales_In_Chennai AS'),
('Select Sum(sales.transactions.sales_amount) from sales.transactions'),
('Inner Join sales.date ON sales.transactions.order_date = sales.date.date'),
('Where sales.date.year = 2020 and sales.transactions.market_code = "Mark001";'),
('#9. Calculate the total number of sales transactions and sales amount in Chennai.'),
('Select * from Sales_In_Chennai;'),
('Create View Distinct_Product AS'),
('Select Distinct product_code From sales.transactions'),
('Where market_code = ''Mark001'';'),
('#10. Find out the Distinct Product Sold in Chennai.'),
('Select * from Distinct_Product;');
